name: Build Kernel

on:
  push:
    branches: [ main-bpf ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bc bison flex make gcc git zip curl

      - name: Download Toolchains and AnyKernel3
        run: |
          mkdir -p ../toolchains
          git clone https://github.com/osm0sis/AnyKernel3 ../AnyKernel3
          curl -L https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/main/clang-r547379.tar.gz -o ../toolchains/aosp-clang.tar.gz
          mkdir -p ../toolchains/aosp-clang
          tar -xf ../toolchains/aosp-clang.tar.gz -C ../toolchains/aosp-clang --strip-components=1

      - name: Build Kernel
        run: |
          echo 2 | bash compile alioth aosp
