name: Build Kernel

on:
  push:
    branches: [ main-bpf ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bc bison flex make gcc git zip curl ccache

      - name: Cache Toolchains
        id: cache-toolchains
        uses: actions/cache@v4
        with:
          path: |
            toolchains
            AnyKernel3
          key: toolchains-aosp-clang-22-${{ runner.os }}

      - name: Download Toolchains and AnyKernel3
        if: steps.cache-toolchains.outputs.cache-hit != 'true'
        run: |
          mkdir -p toolchains
          git clone https://github.com/osm0sis/AnyKernel3 AnyKernel3
          curl -L https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/main/clang-r547379.tar.gz -o toolchains/aosp-clang.tar.gz
          mkdir -p toolchains/aosp-clang
          tar -xf toolchains/aosp-clang.tar.gz -C toolchains/aosp-clang

      - name: Build Kernel
        run: |
          echo 2 | bash compile alioth aosp

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: kernel-zip
          path: "*.zip"

